"POST /user_account HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 200 964
"GET /favicon.ico HTTP/1.1" 200 964
"POST /user_account HTTP/1.1" 500 59
/Users/ughestaff/Library/CloudStorage/OneDrive-IUInternationalUniversityofAppliedSciences/School/Subjects/In Progress/Project Software Engineering/BloodLoof/2. Development Phase/Django Coding/Codes/Bloodloof_project/settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
- Broken pipe from ('127.0.0.1', 52806)

Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4530
- Broken pipe from ('127.0.0.1', 52808)

Internal Server Error: /user_account
Traceback (most recent call last):
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/ughestaff/Library/CloudStorage/OneDrive-IUInternationalUniversityofAppliedSciences/School/Subjects/In Progress/Project Software Engineering/BloodLoof/2. Development Phase/Django Coding/Codes/authentication/views.py", line 83, in user_account
    password1 = request.POST['password1']
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password1'
"POST /user_account HTTP/1.1" 500 75643
Internal Server Error: /user_account
Traceback (most recent call last):
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'password1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/ughestaff/Library/CloudStorage/OneDrive-IUInternationalUniversityofAppliedSciences/School/Subjects/In Progress/Project Software Engineering/BloodLoof/2. Development Phase/Django Coding/Codes/authentication/views.py", line 83, in user_account
    password1 = request.POST['password1']
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'password1'
"POST /user_account HTTP/1.1" 500 75643
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2993
"GET /static/css/main.css HTTP/1.1" 304 0
"GET /static/Images/Logo.jpeg HTTP/1.1" 304 0
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"GET /static/Images/Background2.jpeg HTTP/1.1" 304 0
"GET /user_account HTTP/1.1" 200 3188
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"POST /user_account HTTP/1.1" 200 9353
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"GET /static/Images/email-box.jpeg HTTP/1.1" 304 0
"GET /change_password_page HTTP/1.1" 200 3613
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"POST /change_password HTTP/1.1" 200 23
"GET / HTTP/1.1" 200 2993
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"GET /user_account HTTP/1.1" 200 3188
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"POST /user_account HTTP/1.1" 200 9353
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"GET /change_password_page HTTP/1.1" 200 3613
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
Internal Server Error: /change_password
Traceback (most recent call last):
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/ughestaff/.local/share/virtualenvs/Codes-vPfYgZ7o/lib/python3.10/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view authentication.views.change_password didn't return an HttpResponse object. It returned None instead.
"POST /change_password HTTP/1.1" 500 64050
"GET / HTTP/1.1" 200 9418
"GET /static/css/main.css HTTP/1.1" 304 0
"GET /static/Images/Logo.jpeg HTTP/1.1" 304 0
"GET /static/Images/img-howitworks-2.jpeg HTTP/1.1" 304 0
"GET /static/Images/Head_Picture.png HTTP/1.1" 200 124574
"GET /static/Images/Lisa.png HTTP/1.1" 200 210470
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"GET /static/Images/Background2.jpeg HTTP/1.1" 304 0
"GET /user_signin HTTP/1.1" 200 3188
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"POST /user_account HTTP/1.1" 200 9353
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"GET /static/Images/email-box.jpeg HTTP/1.1" 304 0
/Users/ughestaff/Library/CloudStorage/OneDrive-IUInternationalUniversityofAppliedSciences/School/Subjects/In Progress/Project Software Engineering/BloodLoof/2. Development Phase/Django Coding/Codes/authentication/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/ughestaff/Library/CloudStorage/OneDrive-IUInternationalUniversityofAppliedSciences/School/Subjects/In Progress/Project Software Engineering/BloodLoof/2. Development Phase/Django Coding/Codes/authentication/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/ughestaff/Library/CloudStorage/OneDrive-IUInternationalUniversityofAppliedSciences/School/Subjects/In Progress/Project Software Engineering/BloodLoof/2. Development Phase/Django Coding/Codes/authentication/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user_account HTTP/1.1" 200 3188
"GET /static/css/main.css HTTP/1.1" 200 1734
- Broken pipe from ('127.0.0.1', 53889)

- Broken pipe from ('127.0.0.1', 53890)

"POST /user_account HTTP/1.1" 200 9353
"GET /static/css/main.css HTTP/1.1" 304 0
"GET /static/Images/email-box.jpeg HTTP/1.1" 304 0
"GET /static/Images/Logo.jpeg HTTP/1.1" 304 0
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"GET /static/Images/Background2.jpeg HTTP/1.1" 200 63576
"GET /change_password_page HTTP/1.1" 200 3613
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"POST /change_password HTTP/1.1" 302 0
"GET /user_signin HTTP/1.1" 200 3497
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
"POST /user_account HTTP/1.1" 200 9353
"GET /static/node_modules/bulma/bulma HTTP/1.1" 404 1932
